language: node_js
node_js: 10
cache:
  directories:
    - node_modules
branches:
  only:
    - master
script:
  - cd app
  - yarn && yarn run build
install: npm install -g firebase-tools
after_success:
  - firebase use --token ${FIREBASE_TOKEN}
  - firebase use --add ${PROJECT_ID}
  - firebase deploy --non-interactive --token "${FIREBASE_TOKEN}"
